Remove Builder from ListItem
gtk-rs/gtk4-rs pull request #439
Opened 2021-06-05 22:55 UTC by Hofer-Julian

It does not make sense there

2021-06-05 23:06 UTC, bilelmoussaoui requested changes

2021-06-05 23:06 UTC, bilelmoussaoui commented on gtk4/Gir.toml
> +[[object]]
The items must be ordered otherwise the CI won't be happy

2021-06-05 23:16 UTC, bilelmoussaoui commented
do you mind disabling the builder for BuilderListItemFactory as well?

2021-06-05 23:26 UTC, bilelmoussaoui commented
You need to update your gir submodule. The versions files changes shouldn't occur as gir was updated today.

2021-06-13 09:58 UTC, bilelmoussaoui commented
I have replaced it with #457

2021-06-13 09:58 UTC, closed without merging

2021-06-13 10:23 UTC, Hofer-Julian commented
Thanks